### ISSUE TITLE
Can not access sample data url

### ISSUE THREAD

**Issue by shengjun-zh** [ikomachi226/mysql-heatwave-workshop_jp#1]
こちらのURLが失効したようです、お手数ですがご確認いただけませんか？

Lab 4: 踏み台サーバーにMySQL Shellをインストール、サンプルデータのダウンロード

wget https://objectstorage.us-ashburn-1.oraclecloud.com/p/Ei__e51gGpufa2PI6tVUAkWS2lDT3HGeDqnGTKyM2HEWjH1gHMvfoLCBvaq26LXO/n/idazzjlcjqzj/b/workshop/o/heatwave_workshop.zip

**Comment by ikomachi226** [comment]
アップデートしました。

wget https://objectstorage.us-ashburn-1.oraclecloud.com/p/kr3LRMfdmGqcs4gg0QcUVXm7Fe0ClNfL3RLYTAZK8E1Umz-ZOBcLzaQwds1ZfW7I/n/idazzjlcjqzj/b/heatwave-workshop/o/heatwave_workshop.zip

**Comment by shengjun-zh** [comment]
Thank you!
